--CREATE OR REPLACE TABLE `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.20220713_CR_TIQUETES_AVERIA_2021-01_A_2022-06_D` AS
WITH TIQUETESAVERIAS_2022 AS(
SELECT SITE
    , CLASE
    , MOTIVO
    , CANAL_DE_ATENCI__N AS CANAL_DE_ATENCION
    , TIPO_DE_GESTION
    , TIQUETE
    , DATE(APERTURA) AS FECHA_APERTURA
    , ESTADO
    , AREA_MOTIVO AS AREA
    , SUBAREA
    , CONTRATO
    , PROVINCIA
    , CANTON
    , DISTRITO
    , BARRIO
    , DATE(FECHA_DE_FINALIZACION) AS FECHA_FINALIZACION
    , CLIENTE
    , PRODUCTO_RELACIONADO AS ACTIVO
    , TIPO_ATENCI__N as TIPO_ATENCION


 FROM  `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.20220602_CR_TIQUETES_AVERIA_PREL`
 WHERE EXTRACT (YEAR FROM APERTURA) = 2022 OR DATE_TRUNC(APERTURA,MONTH)="2021-12-01 00:00:00 UTC"
),

TIQUETESAVERIAS_2021 AS(

SELECT *
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-04-12_CR_TIQUETES_AVERIAS_2021-01_A_2022-02_D` 
WHERE EXTRACT(YEAR FROM FECHA_APERTURA) = 2021
ORDER BY 1
)

, TIQUETESMAYO AS(
  SELECT SITE
    , CLASE
    , MOTIVO
    , CANAL_DE_ATENCI__N AS CANAL_DE_ATENCION
    , TIPO_DE_GESTION
    , TIQUETE
    , DATE(APERTURA) AS FECHA_APERTURA
    , ESTADO
    , AREA_MOTIVO AS AREA
    , SUBAREA
    , CONTRATO
    , PROVINCIA
    , CANTON
    , DISTRITO
    , BARRIO
    , DATE(FECHA_DE_FINALIZACION) AS FECHA_FINALIZACION
    , CLIENTE
    , PRODUCTO_RELACIONADO AS ACTIVO
    , TIPO_ATENCI__N as TIPO_ATENCION
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.20220623_tiquetes_averia_mayo`
)
, TIQUETESjunio AS(
  SELECT SITE
    , CLASE
    , MOTIVO
    , CANAL_DE_ATENCI__N AS CANAL_DE_ATENCION
    , TIPO_DE_GESTION
    , TIQUETE
    , DATE(APERTURA) AS FECHA_APERTURA
    , ESTADO
    , AREA_MOTIVO AS AREA
    , SUBAREA
    , CONTRATO
    , PROVINCIA
    , CANTON
    , DISTRITO
    , BARRIO
    , DATE(FECHA_DE_FINALIZACION) AS FECHA_FINALIZACION
    , CLIENTE
    , PRODUCTO_RELACIONADO AS ACTIVO
    , TIPO_ATENCI__N as TIPO_ATENCION
   FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.20220713_AveriasTiquetes`
)

SELECT *
FROM 
(SELECT * FROM TIQUETESAVERIAS_2021
UNION ALL
SELECT * FROM TIQUETESAVERIAS_2022
UNION ALL
SELECT * FROM TIQUETESMAYO
UNION ALL
SELECT * FROM TIQUETESjunio)
