--CREATE OR REPLACE TABLE 
--`gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.20220713_CR_ORDENES_SERVICIO_2021-01_A_2022-06_D` AS
WITH 
SERVICEORDERS_2022 AS(
SELECT SITE, CLASE, MOTIVO, CANAL_DE_ATENCI__N AS CANAL_DE_ATENCION, TIPO_DE_GESTION, TIPO_DE_ORDEN AS TIPO_ORDEN, N___DE_ORDEN AS NO_ORDEN
, DATE(CREADO) AS FECHA_APERTURA, SUBMOTIVO, ESTADO, Nombre_del_contrato AS NOMBRE_CONTRATO, PROVINCIA, CANT__N as CANTON, DISTRITO, BARRIO
, DATE(FECHA_DEL_PEDIDO) AS FECHA_PEDIDO, DATE(Fecha_de_finalizaci__n) AS FECHA_FINALIZACION, CANAL, TIPO_CLIENTE
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.20220612_CR_ORDENES_SERVICIO_PREL` 
WHERE EXTRACT (YEAR FROM FECHA_DEL_PEDIDO) = 2022 OR DATE_TRUNC(FECHA_DEL_PEDIDO,MONTH)="2021-12-01 00:00:00 UTC"
)
, SERVICEORDERS_2021 AS(
    SELECT * 
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-12_CR_ORDENES_SERVICIO_2021-01_A_2021-11_D` 
    WHERE EXTRACT (YEAR FROM FECHA_APERTURA) = 2021
)
, SERVICEORDERS_MAYO2022 AS(
  SELECT SITE, CLASE, MOTIVO, CANAL_DE_ATENCI__N AS CANAL_DE_ATENCION, TIPO_DE_GESTION, TIPO_DE_ORDEN AS TIPO_ORDEN, N___DE_ORDEN AS NO_ORDEN
 , DATE(CREADO) AS FECHA_APERTURA, SUBMOTIVO, ESTADO, Nombre_del_contrato AS NOMBRE_CONTRATO, PROVINCIA, CANT__N as CANTON, DISTRITO, BARRIO
 , DATE(FECHA_DEL_PEDIDO) AS FECHA_PEDIDO, DATE(Fecha_de_finalizaci__n) AS FECHA_FINALIZACION, CANAL, TIPO_CLIENTE
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.20220623_Ordenes_serv_mayo`
)

,serviceorders_junio2022 as(
  SELECT SITE, CLASE, MOTIVO, CANAL_DE_ATENCI__N AS CANAL_DE_ATENCION, TIPO_DE_GESTION, TIPO_DE_ORDEN AS TIPO_ORDEN, N___DE_ORDEN AS NO_ORDEN
 , DATE(CREADO) AS FECHA_APERTURA,SUBMOTIVO, ESTADO, Nombre_del_contrato AS NOMBRE_CONTRATO, PROVINCIA, CANT__N as CANTON, DISTRITO, BARRIO
 , DATE(FECHA_DEL_PEDIDO) AS FECHA_PEDIDO, DATE(Fecha_de_finalizaci__n) AS FECHA_FINALIZACION, CANAL, TIPO_CLIENTE
 FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.20220713_ServiceOrders`
 where date_trunc(date(Creado),month)="2022-06-01"
)



SELECT *
FROM
(SELECT * FROM SERVICEORDERS_2021
UNION ALL
SELECT * FROM SERVICEORDERS_2022
UNION ALL
SELECT * FROM SERVICEORDERS_MAYO2022
UNION ALL
SELECT * FROM SERVICEORDERS_junio2022)
