WITH 

ventas AS (
    SELECT DATE_TRUNC(FECHA_INSTALACION,MONTH) AS MONTH_INSTALLATION, COUNT(DISTINCT ACT_ACCT_CD) AS INSTALLATIONS
    FROM (
        SELECT ACT_ACCT_CD, MIN(ACT_ACCT_INST_DT) AS FECHA_INSTALACION
        FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-04-20_Historical_CRM_ene_2021_mar_2022_D`
        GROUP BY 1
    )
    GROUP BY 1
),

churn AS (
    SELECT CONTRATOCRM, CHURNTYPEFLAGSO, MAX(FechaChurn) AS FECHA_CHURN, 
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-03-06_ChurnTypeFlagChurners_D`
    WHERE CHURNTYPEFLAGSO = 'Involuntario'
    GROUP BY 1,2
),

never_paid_flag AS (
SELECT *, DATE_DIFF(CST_CHRN_DT,ACT_ACCT_INST_DT,DAY) AS DAYS_WO_PAYMENT, CASE WHEN DATE_DIFF(CST_CHRN_DT,ACT_ACCT_INST_DT,DAY) <= 119 THEN ACT_ACCT_CD ELSE NULL END AS NEVER_PAID_CUSTOMER
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-04-20_Historical_CRM_ene_2021_mar_2022_D` d
INNER JOIN churn c
    ON d.ACT_ACCT_CD = CAST(c.CONTRATOCRM AS INT) AND d.FECHA_EXTRACCION = DATE(c.FECHA_CHURN)
)

SELECT v.*, COUNT(DISTINCT NEVER_PAID_CUSTOMER) AS NEVER_PAID
FROM ventas v
LEFT JOIN never_paid_flag n
    ON v.MONTH_INSTALLATION = DATE_TRUNC(n.ACT_ACCT_INST_DT,MONTH)
WHERE ACT_ACCT_INST_DT >= '2021-01-01'
GROUP BY 1,2
ORDER BY 1
