WITH 
CRM AS (
SELECT act_acct_cd,PD_VO_PROD_ID, PD_TV_PROD_CD, PD_BB_PROD_NM,C_CUST_AGE,
CASE 
WHEN PD_VO_PROD_ID IS NOT NULL AND PD_BB_PROD_NM IS NOT NULL AND PD_TV_PROD_CD IS NOT NULL THEN "3P"
WHEN PD_VO_PROD_ID IS NULL AND PD_BB_PROD_NM IS NOT NULL AND PD_TV_PROD_CD IS NOT NULL THEN "2P"
WHEN PD_VO_PROD_ID IS NOT NULL AND PD_BB_PROD_NM IS NULL AND PD_TV_PROD_CD IS NOT NULL THEN"2P"
WHEN PD_VO_PROD_ID IS NOT NULL AND PD_BB_PROD_NM IS NOT NULL AND PD_TV_PROD_CD IS NULL THEN"2P"
ELSE "1P" END AS MIX, COUNT(*) AS NumUsuarios
  FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
WHERE safe_cast(fecha_extraccion AS string)="2022-02-27"
GROUP BY 1,2,3,4,5
ORDER BY NumUsuarios

)/*
SELECT PD_BB_PROD_NM, COUNT(*) AS NumUsuarios
FROM CRM
WHERE MIX="3P"
GROUP BY PD_BB_PROD_NM
ORDER BY NumUsuarios desc*/

,TablaEq AS (
    SELECT * FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_CATALOGUE_TV_INTERNET_2021_T`
)

,BBTech AS(
    SELECT act_acct_cd,PD_VO_PROD_ID,PD_BB_PROD_NM,PD_TV_PROD_CD,ActivoInternet,Tipo_Tecnologia, Mix, C_CUST_AGE
    from CRM c LEFT JOIN TablaEq ON PD_BB_PROD_NM=ActivoInternet
)
/*
SELECT PD_BB_PROD_NM, COUNT(*) AS NumClientes
FROM BBTech
WHERE PD_BB_PROD_NM is not null AND Tipo_Tecnologia is null
GROUP BY PD_BB_PROD_NM
ORDER BY NumClientes desc*/

,OtrosTech AS (
    SELECT act_acct_cd, MIX,C_CUST_AGE,
    CASE 
    WHEN Tipo_Tecnologia IS NOT NULL THEN Tipo_Tecnologia
    WHEN Tipo_Tecnologia IS NULL AND PD_TV_PROD_CD="NextGenTV" THEN "FTTH"
    ELSE "HFC" END AS TechAdj,
    CASE
    WHEN C_CUST_AGE <=6 THEN "EARLY TENURE"
    WHEN C_CUST_AGE >6 THEN "LATE TENURE"
    ELSE NULL END AS TENURE
    FROM BBTech
)

SELECT Mix,TENURE, COUNT(*) AS NumClientes
FROM OtrosTech
GROUP BY MIX, TENURE
ORDER BY NumClientes desc
